/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WotdRouteImport } from './routes/wotd'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as RandomRouteImport } from './routes/random'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GlossaryRouteImport } from './routes/glossary'
import { Route as ChallengingRouteImport } from './routes/challenging'
import { Route as AdminDashboardRouteImport } from './routes/admin-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const WotdRoute = WotdRouteImport.update({
  id: '/wotd',
  path: '/wotd',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const RandomRoute = RandomRouteImport.update({
  id: '/random',
  path: '/random',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GlossaryRoute = GlossaryRouteImport.update({
  id: '/glossary',
  path: '/glossary',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengingRoute = ChallengingRouteImport.update({
  id: '/challenging',
  path: '/challenging',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/challenging': typeof ChallengingRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/success': typeof SuccessRoute
  '/wotd': typeof WotdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/challenging': typeof ChallengingRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/success': typeof SuccessRoute
  '/wotd': typeof WotdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-dashboard': typeof AdminDashboardRoute
  '/challenging': typeof ChallengingRoute
  '/glossary': typeof GlossaryRoute
  '/login': typeof LoginRoute
  '/random': typeof RandomRoute
  '/success': typeof SuccessRoute
  '/wotd': typeof WotdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-dashboard'
    | '/challenging'
    | '/glossary'
    | '/login'
    | '/random'
    | '/success'
    | '/wotd'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-dashboard'
    | '/challenging'
    | '/glossary'
    | '/login'
    | '/random'
    | '/success'
    | '/wotd'
  id:
    | '__root__'
    | '/'
    | '/admin-dashboard'
    | '/challenging'
    | '/glossary'
    | '/login'
    | '/random'
    | '/success'
    | '/wotd'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ChallengingRoute: typeof ChallengingRoute
  GlossaryRoute: typeof GlossaryRoute
  LoginRoute: typeof LoginRoute
  RandomRoute: typeof RandomRoute
  SuccessRoute: typeof SuccessRoute
  WotdRoute: typeof WotdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wotd': {
      id: '/wotd'
      path: '/wotd'
      fullPath: '/wotd'
      preLoaderRoute: typeof WotdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/random': {
      id: '/random'
      path: '/random'
      fullPath: '/random'
      preLoaderRoute: typeof RandomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/glossary': {
      id: '/glossary'
      path: '/glossary'
      fullPath: '/glossary'
      preLoaderRoute: typeof GlossaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenging': {
      id: '/challenging'
      path: '/challenging'
      fullPath: '/challenging'
      preLoaderRoute: typeof ChallengingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-dashboard': {
      id: '/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin-dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ChallengingRoute: ChallengingRoute,
  GlossaryRoute: GlossaryRoute,
  LoginRoute: LoginRoute,
  RandomRoute: RandomRoute,
  SuccessRoute: SuccessRoute,
  WotdRoute: WotdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
